# Data preparation for the hello_world example

from sqlalchemy import create_engine
from cubes.tutorial.sql import create_table_from_csv

# 1. Prepare SQL data in memory

FACT_TABLE = "oecd_crs"

print "preparing data..."

engine = create_engine('sqlite:///data.sqlite')
fields1=[
("Year", "integer"),
("donorcode", "integer"),
("donorname", "string"),
("agencycode", "integer"),
("agencyname", "string"),
("crsid", "integer"),
("projectnumber", "integer"),
("initialreport", "string"),
("recipientcode", "integer"),
("recipientname", "string"),
("regioncode", "integer"),
("regionname", "string"),
("incomegroupcode", "string"),
("incomegroupname", "string"),
("flowcode", "string"),
("flowname", "string"),
("bi_multi", "string"),
("category", "string"),
("finance_t", "string"),
("aid_t", "string"),
("usd_commitment", "string"),
("usd_disbursement", "string"),
("usd_received", "string"),
("usd_commitment_defl", "string"),
("usd_disbursement_defl", "string"),
("usd_received_defl", "string"),
("usd_adjustment", "string"),
("usd_adjustment_defl", "string"),
("usd_amountuntied", "string"),
("usd_amountpartialtied", "string"),
("usd_amounttied", "string"),
("usd_amountuntied_defl", "string"),
("usd_amountpartialtied_defl", "string"),
("usd_amounttied_defl", "string"),
("usd_IRTC", "string"),
("usd_expert_commitment", "string"),
("usd_expert_extended", "string"),
("usd_export_credit", "string"),
("currencycode", "string"),
("commitment_national", "string"),
("disbursement_national", "string"),
("shortdescription", "string"),
("projecttitle", "string"),
("purposecode", "string"),
("purposename", "string"),
("sectorcode", "string"),
("sectorname", "string"),
("channelcode", "string"),
("channelname", "string"),
("channelreportedname", "string"),
("geography", "string"),
("expectedstartdate", "string"),
("completiondate", "string"),
("longdescription", "string"),
("gender", "string"),
("environment", "string"),
("trade", "string"),
("pdgg", "string"),
("FTC", "string"),
("PBA", "string"),
("investmentproject", "string"),
("assocfinance", "string"),
("biodiversity", "string"),
("climateMitigation", "string"),
("climateAdaptation", "string"),
("desertification", "string"),
("typerepayment", "string"),
("numberrepayment", "string"),
("interest1", "string"),
("interest2", "string"),
("repaydate1", "string"),
("repaydate2", "string"),
("grantelement", "string"),
("usd_interest", "string"),
("usd_outstanding", "string"),
("usd_arrears_principal", "string"),
("usd_arrears_interest", "string"),
("usd_future_DS_principal", "string"),
("usd_future_DS_interest", "string")]
fields2=[
        ("year", "string"),
        ("donorcode", "string"),
        ("donorname", "string"),
        ("agencycode", "string"),
        ("agencyname", "string"),
        ("crsid", "string"),
        ("projectnumber", "string"),
        ("initialreport", "string"),
        ("recipientname", "string")]
create_table_from_csv(engine,
                      "sample.csv",
                      table_name=FACT_TABLE,
                      fields=fields1,
                      create_id=True
                  )

print "done. file data.sqlite created"
